language: python

python:
  - "2.7"
  - "3.8"

env:
  - MYSQL_USER=travis MYSQL_PASSWORD=

services:
  - mysql
  - memcached

before_script:
  - mysql -e 'set global innodb_large_prefix=1'
  - mysql -e 'drop database if exists test_olo'
  - mysql -e 'create database test_olo'
  - mysql -e 'grant all on *.* to travis@localhost'
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - pip install pylint==1.9.2 codecov

script:
  - pylint --rcfile=.pylintrc olo
  - pytest --cov=olo

after_success:
  - codecov
